### ISSUE TITLE
Support dynamic activity and workflow implementations

### ISSUE THREAD

**Issue by vidath** [temporalio/sdk-python#292] opened 2023-03-02 20:06 UTC
s your feature request related to a problem? Please describe.
In some cases, activity and workflow implementations should be loaded dynamically. It is similar to the way the Java app engines load applications using class loaders.

Describe the solution you'd like
Expose an extension point for dynamic activity loading. While the SDK might not provide the explicit loading mechanism it should provide a factory interface that is called with activity or workflow type to provide an untyped activity implementation.

Additional context
This feature has been added to java sdk as part of issue #245
https://github.com/temporalio/sdk-java/issues/245

https://community.temporal.io/t/dynamic-activities-registration-at-runtime-and-worker-splitting/930/7

**Comment by cretz** [comment] 2023-03-02 20:06
Closing as duplicate of #242

**Closed by cretz** 2023-03-02 20:06 UTC
Labels: enhancement
